# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from golang v1.11 base image
FROM golang:1.11 as builder

# Add Maintainer Info
LABEL maintainer="fams@linuxplace.com.br"

# Set the Current Working Directory inside the container
WORKDIR /go/src/github.com/fams/linuxplace-docker

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY myweb.go .

# Download dependencies
RUN go get -d -v ./...

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/myweb .


######## Start a new stage from scratch #######
FROM scratch

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /go/bin/myweb .
COPY Docker/ .

EXPOSE 8080

CMD ["./myweb"] 

